name: Oracle Cloud Free ARM Instance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Otomatik arka plan zamanlayıcısı
  workflow_dispatch:        # El ile manuel başlatma butonu (Run workflow)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install OCI CLI
      run: |
        pip install oci-cli

    - name: Run Oracle Creator Script
      env:
        # GitHub Secrets içindeki verileri bota güvenle aktarıyoruz
        USER_ID: ${{ secrets.USER_ID }}
        FINGERPRINT: ${{ secrets.FINGERPRINT }}
        TENANCY_ID: ${{ secrets.TENANCY_ID }}
        SUBNET_ID: ${{ secrets.SUBNET_ID }}
        IMAGE_ID: ${{ secrets.IMAGE_ID }}
        SSH_AUTHORIZED_KEYS: ${{ secrets.SSH_AUTHORIZED_KEYS }}
        AVAILABILITY_DOMAIN: ${{ secrets.AVAILABILITY_DOMAIN }}
        SHAPE: ${{ secrets.SHAPE }}
      run: |
        chmod +x oracle_cloud_instance_creator.sh
        ./oracle_cloud_instance_creator.sh
